import type { Exercise } from "$lib/types";

export const defaultExerciseLibraryVersion = 1;

function defineExercise(
  id: string,
  name: string,
  muscles: string[],
  equipment: string,
  description: string,
): Exercise {
  return {
    id,
    name,
    muscles,
    equipment,
    guideUrl: `https://www.youtube.com/results?search_query=${encodeURIComponent(`${name} form`)}`,
    description,
  };
}

export const defaultExercises: Exercise[] = [
  defineExercise(
    "barbell-bench-press",
    "Barbell bench press",
    ["Chest", "Triceps", "Front delts"],
    "Barbell",
    "Plant your feet, keep your shoulder blades set, and lower the bar to your lower chest.",
  ),
  defineExercise(
    "incline-dumbbell-press",
    "Incline dumbbell press",
    ["Upper chest", "Triceps", "Front delts"],
    "Dumbbells",
    "Use a shallow incline and lower the dumbbells with control to chest height.",
  ),
  defineExercise(
    "cable-fly",
    "Cable fly",
    ["Chest"],
    "Cable machine",
    "Keep a soft elbow bend and bring the handles together in a wide arc.",
  ),
  defineExercise(
    "tricep-pushdown",
    "Rope tricep pushdown",
    ["Triceps"],
    "Cable machine",
    "Keep your elbows close to your sides and separate the rope at the bottom.",
  ),
  defineExercise(
    "lateral-raise",
    "Dumbbell lateral raise",
    ["Side delts"],
    "Dumbbells",
    "Lead with your elbows and raise only to shoulder height.",
  ),
  defineExercise(
    "assisted-pullup",
    "Assisted pull-up",
    ["Lats", "Upper back", "Biceps"],
    "Machine",
    "Start from a long-arm position and drive your elbows down toward your ribs.",
  ),
  defineExercise(
    "dumbbell-bench-press",
    "Dumbbell bench press",
    ["Chest", "Triceps", "Front delts"],
    "Dumbbells",
    "Keep your shoulder blades against the bench and press the dumbbells over your chest.",
  ),
  defineExercise(
    "incline-barbell-bench-press",
    "Incline barbell bench press",
    ["Upper chest", "Triceps", "Front delts"],
    "Barbell",
    "Use a low incline and lower the bar under control toward your upper chest.",
  ),
  defineExercise(
    "push-up",
    "Push-up",
    ["Chest", "Triceps", "Front delts", "Core"],
    "Bodyweight",
    "Keep a straight body line and lower your chest between your hands.",
  ),
  defineExercise(
    "chest-dip",
    "Chest dip",
    ["Chest", "Triceps", "Front delts"],
    "Dip bars",
    "Lean slightly forward and lower only as far as your shoulders stay comfortable.",
  ),
  defineExercise(
    "pec-deck",
    "Pec deck",
    ["Chest"],
    "Pec deck",
    "Keep your back against the pad and bring your arms together without shrugging.",
  ),
  defineExercise(
    "machine-chest-press",
    "Machine chest press",
    ["Chest", "Triceps", "Front delts"],
    "Chest press machine",
    "Set the handles near mid-chest and press without lifting your shoulders.",
  ),
  defineExercise(
    "pull-up",
    "Pull-up",
    ["Lats", "Upper back", "Biceps"],
    "Pull-up bar",
    "Pull your chest toward the bar while driving your elbows down.",
  ),
  defineExercise(
    "chin-up",
    "Chin-up",
    ["Lats", "Biceps", "Upper back"],
    "Pull-up bar",
    "Use an underhand grip and pull without swinging or reaching your chin forward.",
  ),
  defineExercise(
    "lat-pulldown",
    "Lat pulldown",
    ["Lats", "Upper back", "Biceps"],
    "Lat pulldown machine",
    "Keep your torso steady and pull the bar toward your upper chest.",
  ),
  defineExercise(
    "barbell-row",
    "Barbell row",
    ["Upper back", "Lats", "Biceps", "Lower back"],
    "Barbell",
    "Brace in a hinged position and row the bar toward your lower ribs.",
  ),
  defineExercise(
    "one-arm-dumbbell-row",
    "One-arm dumbbell row",
    ["Lats", "Upper back", "Biceps"],
    "Dumbbells",
    "Keep your torso square and pull your elbow toward your hip.",
  ),
  defineExercise(
    "seated-cable-row",
    "Seated cable row",
    ["Upper back", "Lats", "Biceps"],
    "Cable machine",
    "Stay tall and pull the handle toward your lower ribs without leaning back.",
  ),
  defineExercise(
    "chest-supported-row",
    "Chest-supported row",
    ["Upper back", "Lats", "Biceps", "Rear delts"],
    "Dumbbells",
    "Keep your chest on the bench and row without lifting your shoulders.",
  ),
  defineExercise(
    "t-bar-row",
    "T-bar row",
    ["Upper back", "Lats", "Biceps"],
    "Landmine",
    "Brace your trunk and pull the bar toward your lower chest.",
  ),
  defineExercise(
    "face-pull",
    "Face pull",
    ["Rear delts", "Upper back", "Rotator cuff"],
    "Cable machine",
    "Pull the rope toward eye level and finish with your hands beside your face.",
  ),
  defineExercise(
    "reverse-pec-deck",
    "Reverse pec deck",
    ["Rear delts", "Upper back"],
    "Reverse pec deck",
    "Keep your chest against the pad and sweep your arms outward.",
  ),
  defineExercise(
    "barbell-shrug",
    "Barbell shrug",
    ["Traps"],
    "Barbell",
    "Lift your shoulders straight up and lower them under control.",
  ),
  defineExercise(
    "back-extension",
    "Back extension",
    ["Lower back", "Glutes", "Hamstrings"],
    "Back extension bench",
    "Hinge at the hips and finish in a straight line without overextending your back.",
  ),
  defineExercise(
    "barbell-overhead-press",
    "Barbell overhead press",
    ["Front delts", "Side delts", "Triceps"],
    "Barbell",
    "Brace your trunk and press the bar overhead without leaning back.",
  ),
  defineExercise(
    "dumbbell-shoulder-press",
    "Dumbbell shoulder press",
    ["Front delts", "Side delts", "Triceps"],
    "Dumbbells",
    "Press upward while keeping your ribs down and forearms vertical.",
  ),
  defineExercise(
    "arnold-press",
    "Arnold press",
    ["Front delts", "Side delts", "Triceps"],
    "Dumbbells",
    "Rotate smoothly as you press and keep the movement controlled.",
  ),
  defineExercise(
    "cable-lateral-raise",
    "Cable lateral raise",
    ["Side delts"],
    "Cable machine",
    "Raise your arm out to the side without leaning or shrugging.",
  ),
  defineExercise(
    "rear-delt-fly",
    "Dumbbell rear delt fly",
    ["Rear delts", "Upper back"],
    "Dumbbells",
    "Hinge forward and open your arms while keeping your shoulders down.",
  ),
  defineExercise(
    "barbell-curl",
    "Barbell curl",
    ["Biceps", "Forearms"],
    "Barbell",
    "Keep your elbows near your sides and curl without swinging your torso.",
  ),
  defineExercise(
    "dumbbell-curl",
    "Dumbbell curl",
    ["Biceps", "Forearms"],
    "Dumbbells",
    "Curl with a still upper arm and turn your palm upward as you lift.",
  ),
  defineExercise(
    "hammer-curl",
    "Hammer curl",
    ["Biceps", "Brachialis", "Forearms"],
    "Dumbbells",
    "Keep a neutral grip and avoid moving your elbows forward.",
  ),
  defineExercise(
    "incline-dumbbell-curl",
    "Incline dumbbell curl",
    ["Biceps"],
    "Dumbbells",
    "Let your arms hang behind your torso and curl without lifting your shoulders.",
  ),
  defineExercise(
    "preacher-curl",
    "Preacher curl",
    ["Biceps", "Brachialis"],
    "Preacher bench",
    "Keep your upper arms on the pad and stop before your elbows lock hard.",
  ),
  defineExercise(
    "cable-curl",
    "Cable curl",
    ["Biceps"],
    "Cable machine",
    "Keep steady tension and curl with your elbows fixed by your sides.",
  ),
  defineExercise(
    "overhead-triceps-extension",
    "Overhead triceps extension",
    ["Triceps"],
    "Dumbbells",
    "Keep your elbows pointed forward and extend without arching your back.",
  ),
  defineExercise(
    "skull-crusher",
    "EZ-bar skull crusher",
    ["Triceps"],
    "EZ curl bar",
    "Keep your upper arms steady and lower the bar behind your forehead.",
  ),
  defineExercise(
    "close-grip-bench-press",
    "Close-grip bench press",
    ["Triceps", "Chest", "Front delts"],
    "Barbell",
    "Use a comfortable close grip and keep your elbows near your body.",
  ),
  defineExercise(
    "bench-dip",
    "Bench dip",
    ["Triceps", "Chest", "Front delts"],
    "Flat bench",
    "Keep your hips close to the bench and use a comfortable shoulder depth.",
  ),
  defineExercise(
    "back-squat",
    "Barbell back squat",
    ["Quadriceps", "Glutes", "Hamstrings", "Core"],
    "Barbell",
    "Brace before descending and keep your whole foot planted as you stand.",
  ),
  defineExercise(
    "front-squat",
    "Front squat",
    ["Quadriceps", "Glutes", "Core"],
    "Barbell",
    "Keep your elbows high and torso upright while sitting between your hips.",
  ),
  defineExercise(
    "goblet-squat",
    "Goblet squat",
    ["Quadriceps", "Glutes", "Core"],
    "Dumbbells",
    "Hold the weight close to your chest and keep your feet planted.",
  ),
  defineExercise(
    "leg-press",
    "Leg press",
    ["Quadriceps", "Glutes", "Hamstrings"],
    "Leg press",
    "Lower the platform only as far as your pelvis stays against the pad.",
  ),
  defineExercise(
    "hack-squat",
    "Hack squat",
    ["Quadriceps", "Glutes"],
    "Hack squat machine",
    "Keep your back on the pad and drive through your whole foot.",
  ),
  defineExercise(
    "bulgarian-split-squat",
    "Bulgarian split squat",
    ["Quadriceps", "Glutes", "Hamstrings"],
    "Dumbbells",
    "Lower straight down with most of your weight over the front leg.",
  ),
  defineExercise(
    "walking-lunge",
    "Walking lunge",
    ["Quadriceps", "Glutes", "Hamstrings"],
    "Dumbbells",
    "Take controlled steps and keep your front knee tracking over your foot.",
  ),
  defineExercise(
    "reverse-lunge",
    "Reverse lunge",
    ["Quadriceps", "Glutes", "Hamstrings"],
    "Dumbbells",
    "Step back far enough to lower with a stable front foot.",
  ),
  defineExercise(
    "step-up",
    "Step-up",
    ["Quadriceps", "Glutes"],
    "Plyometric box",
    "Drive through the working foot and avoid pushing off the floor leg.",
  ),
  defineExercise(
    "leg-extension",
    "Leg extension",
    ["Quadriceps"],
    "Leg extension machine",
    "Align your knees with the machine pivot and extend without swinging.",
  ),
  defineExercise(
    "conventional-deadlift",
    "Conventional deadlift",
    ["Hamstrings", "Glutes", "Lower back", "Upper back", "Forearms"],
    "Barbell",
    "Brace with the bar over mid-foot and stand by pushing the floor away.",
  ),
  defineExercise(
    "romanian-deadlift",
    "Romanian deadlift",
    ["Hamstrings", "Glutes", "Lower back"],
    "Barbell",
    "Push your hips back while keeping the bar close to your legs.",
  ),
  defineExercise(
    "sumo-deadlift",
    "Sumo deadlift",
    ["Glutes", "Hamstrings", "Quadriceps", "Lower back"],
    "Barbell",
    "Set a wide stance, brace, and push your knees out as you stand.",
  ),
  defineExercise(
    "hip-thrust",
    "Barbell hip thrust",
    ["Glutes", "Hamstrings"],
    "Barbell",
    "Drive through your heels and finish with your ribs down and hips extended.",
  ),
  defineExercise(
    "glute-bridge",
    "Glute bridge",
    ["Glutes", "Hamstrings"],
    "Bodyweight",
    "Press through your feet and squeeze your glutes without arching your back.",
  ),
  defineExercise(
    "lying-leg-curl",
    "Lying leg curl",
    ["Hamstrings"],
    "Lying leg curl machine",
    "Keep your hips against the pad and curl without lifting your lower back.",
  ),
  defineExercise(
    "seated-leg-curl",
    "Seated leg curl",
    ["Hamstrings"],
    "Seated leg curl machine",
    "Keep your thighs secured and curl through a controlled range.",
  ),
  defineExercise(
    "good-morning",
    "Barbell good morning",
    ["Hamstrings", "Glutes", "Lower back"],
    "Barbell",
    "Brace and hinge at the hips while keeping a soft bend in your knees.",
  ),
  defineExercise(
    "cable-kickback",
    "Cable glute kickback",
    ["Glutes"],
    "Cable machine",
    "Keep your pelvis square and move the leg without arching your back.",
  ),
  defineExercise(
    "hip-abduction",
    "Machine hip abduction",
    ["Glutes", "Hip abductors"],
    "Hip abduction machine",
    "Open your knees under control while keeping your torso steady.",
  ),
  defineExercise(
    "hip-adduction",
    "Machine hip adduction",
    ["Hip adductors"],
    "Hip adduction machine",
    "Bring your legs together smoothly without bouncing the stack.",
  ),
  defineExercise(
    "standing-calf-raise",
    "Standing calf raise",
    ["Calves"],
    "Standing calf raise machine",
    "Use a full heel drop and rise onto the balls of your feet without bouncing.",
  ),
  defineExercise(
    "seated-calf-raise",
    "Seated calf raise",
    ["Calves"],
    "Seated calf raise machine",
    "Pause at the bottom and top while keeping the movement controlled.",
  ),
  defineExercise(
    "plank",
    "Plank",
    ["Core"],
    "Bodyweight",
    "Hold a straight body line while breathing and keeping your ribs down.",
  ),
  defineExercise(
    "side-plank",
    "Side plank",
    ["Core", "Obliques"],
    "Bodyweight",
    "Stack your hips and shoulders while keeping your body in a straight line.",
  ),
  defineExercise(
    "crunch",
    "Crunch",
    ["Core"],
    "Floor",
    "Curl your ribs toward your pelvis without pulling on your neck.",
  ),
  defineExercise(
    "cable-crunch",
    "Cable crunch",
    ["Core"],
    "Cable machine",
    "Keep your hips still and curl your ribs toward your pelvis.",
  ),
  defineExercise(
    "hanging-leg-raise",
    "Hanging leg raise",
    ["Core", "Hip flexors", "Forearms"],
    "Pull-up bar",
    "Raise your legs without swinging and finish by curling your pelvis upward.",
  ),
  defineExercise(
    "ab-wheel-rollout",
    "Ab wheel rollout",
    ["Core", "Lats"],
    "Ab wheel",
    "Keep your ribs down and roll only as far as you can control your spine.",
  ),
  defineExercise(
    "russian-twist",
    "Russian twist",
    ["Core", "Obliques"],
    "Medicine ball",
    "Rotate through your torso under control instead of swinging the weight.",
  ),
  defineExercise(
    "kettlebell-swing",
    "Kettlebell swing",
    ["Glutes", "Hamstrings", "Core", "Forearms"],
    "Kettlebell",
    "Hinge sharply and let hip drive move the bell rather than lifting with your arms.",
  ),
  defineExercise(
    "farmers-carry",
    "Farmer's carry",
    ["Forearms", "Traps", "Core"],
    "Dumbbells",
    "Walk tall with short controlled steps and keep the weights from swinging.",
  ),
  defineExercise(
    "burpee",
    "Burpee",
    ["Full body"],
    "Bodyweight",
    "Move through each position under control and use a pace you can maintain.",
  ),
];

export const defaultExerciseIds = new Set(
  defaultExercises.map((exercise) => exercise.id),
);
