export const muscleOptions = [
  "Full body",
  "Chest",
  "Upper chest",
  "Lower chest",
  "Pectoralis major",
  "Pectoralis minor",
  "Back",
  "Lats",
  "Upper back",
  "Lower back",
  "Traps",
  "Rhomboids",
  "Teres major",
  "Erector spinae",
  "Shoulders",
  "Front delts",
  "Side delts",
  "Rear delts",
  "Rotator cuff",
  "Supraspinatus",
  "Infraspinatus",
  "Arms",
  "Biceps",
  "Brachialis",
  "Brachioradialis",
  "Triceps",
  "Forearms",
  "Wrist flexors",
  "Wrist extensors",
  "Grip",
  "Legs",
  "Quadriceps",
  "Rectus femoris",
  "Vastus lateralis",
  "Vastus medialis",
  "Hamstrings",
  "Biceps femoris",
  "Semitendinosus",
  "Semimembranosus",
  "Glutes",
  "Gluteus maximus",
  "Gluteus medius",
  "Gluteus minimus",
  "Hip flexors",
  "Hip adductors",
  "Hip abductors",
  "Tensor fasciae latae",
  "Calves",
  "Gastrocnemius",
  "Soleus",
  "Tibialis anterior",
  "Core",
  "Rectus abdominis",
  "Obliques",
  "Transverse abdominis",
  "Serratus anterior",
  "Neck",
] as const;

export const equipmentOptions = [
  "No equipment",
  "Bodyweight",
  "Floor",
  "Wall",
  "Partner",
  "Barbell",
  "Dumbbells",
  "Adjustable dumbbells",
  "Kettlebell",
  "EZ curl bar",
  "Trap bar",
  "Safety squat bar",
  "Swiss bar",
  "Cambered bar",
  "Landmine",
  "Weight plates",
  "Resistance band",
  "Mini band",
  "Loop band",
  "Cable machine",
  "Functional trainer",
  "Single cable stack",
  "Dual cable stack",
  "Lat pulldown machine",
  "Seated row machine",
  "Selectorized machine",
  "Plate-loaded machine",
  "Smith machine",
  "Chest press machine",
  "Shoulder press machine",
  "Pec deck",
  "Reverse pec deck",
  "Biceps curl machine",
  "Triceps extension machine",
  "Leg press",
  "Hack squat machine",
  "Pendulum squat",
  "Belt squat machine",
  "Leg extension machine",
  "Seated leg curl machine",
  "Lying leg curl machine",
  "Standing leg curl machine",
  "Hip thrust machine",
  "Hip abduction machine",
  "Hip adduction machine",
  "Glute kickback machine",
  "Standing calf raise machine",
  "Seated calf raise machine",
  "Squat rack",
  "Power rack",
  "Half rack",
  "Pull-up bar",
  "Dip bars",
  "Gymnastic rings",
  "Suspension trainer",
  "Flat bench",
  "Adjustable bench",
  "Preacher bench",
  "Roman chair",
  "GHD",
  "Back extension bench",
  "Captain's chair",
  "Ab wheel",
  "Foam roller",
  "Massage ball",
  "Stability ball",
  "BOSU ball",
  "Medicine ball",
  "Slam ball",
  "Swiss ball",
  "Plyometric box",
  "Step platform",
  "Sled",
  "Prowler",
  "Battle ropes",
  "Climbing rope",
  "Sandbag",
  "Bulgarian bag",
  "Weighted vest",
  "Dip belt",
  "Ankle weights",
  "Wrist roller",
  "Hand gripper",
  "Macebell",
  "Clubbell",
  "Tire",
  "Sledgehammer",
  "Treadmill",
  "Stationary bike",
  "Air bike",
  "Rowing ergometer",
  "Ski ergometer",
  "Elliptical",
  "Stair climber",
  "Pool",
] as const;
